src/Entity/Evenement.php
<?php

namespace App\Entity;

use App\Repository\EvenementRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EvenementRepository::class)
 */
class Evenement
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $Sport_id;

    /**
     * @ORM\Column(type="integer")
     */
    private $Type_id;

    /**
     * @ORM\Column(type="integer")
     */
    private $Categorie_id;

    /**
     * @ORM\Column(type="string", length=45)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_debut;

    /**
     * @ORM\Column(type="integer")
     */
    private $nombre_places;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $vignette;

    /**
     * @ORM\Column(type="integer")
     */
    private $duree;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_fin;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, inversedBy="evenement")
     */
    private $User;

    public function __construct()
    {
        $this->User = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSportId(): ?int
    {
        return $this->Sport_id;
    }

    public function setSportId(int $Sport_id): self
    {
        $this->Sport_id = $Sport_id;

        return $this;
    }

    public function getTypeId(): ?int
    {
        return $this->Type_id;
    }

    public function setTypeId(int $Type_id): self
    {
        $this->Type_id = $Type_id;

        return $this;
    }

    public function getCategorieId(): ?int
    {
        return $this->Categorie_id;
    }

    public function setCategorieId(int $Categorie_id): self
    {
        $this->Categorie_id = $Categorie_id;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getNombrePlaces(): ?int
    {
        return $this->nombre_places;
    }

    public function setNombrePlaces(int $nombre_places): self
    {
        $this->nombre_places = $nombre_places;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getVignette(): ?string
    {
        return $this->vignette;
    }

    public function setVignette(string $vignette): self
    {
        $this->vignette = $vignette;

        return $this;
    }

    public function getDuree(): ?int
    {
        return $this->duree;
    }

    public function setDuree(int $duree): self
    {
        $this->duree = $duree;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUser(): Collection
    {
        return $this->User;
    }

    public function addUser(User $user): self
    {
        if (!$this->User->contains($user)) {
            $this->User[] = $user;
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        $this->User->removeElement($user);

        return $this;
    }
}

src/Form/EvenementType.php
<?php

namespace App\Form;

use App\Entity\Evenement;
use Doctrine\DBAL\Types\TextType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EvenementType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Sport_id')
            ->add('Type_id')
            ->add('Categorie_id')
            ->add('nom')
            ->add('description')
            ->add('date_debut')
            ->add('nombre_places')
            ->add('image')
            ->add('vignette')
            ->add('duree')
            ->add('date_fin')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Evenement::class,
        ]);
    }
}

src/Controller/EvenementController.php
<?php

namespace App\Controller;

use App\Entity\Evenement;
use App\Form\EvenementType;
use App\Repository\EvenementRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/evenement")
 */
class EvenementController extends AbstractController
{
    /**
     * @Route("/", name="evenement_index", methods={"GET"})
     */
    public function index(EvenementRepository $evenementRepository): Response
    {
        return $this->render('evenement/index.html.twig', [
            'evenements' => $evenementRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="evenement_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        //On instancie un nouvel evenement
        $evenement = new Evenement();
        //Méthode qui génere le form
        $form = $this->createForm(EvenementType::class, $evenement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($evenement);
            $entityManager->flush();

            return $this->redirectToRoute('evenement_index');
        }

        return $this->render('evenement/new.html.twig', [
            'evenement' => $evenement,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="evenement_show", methods={"GET"})
     */
    public function show(Evenement $evenement): Response
    {
        return $this->render('evenement/show.html.twig', [
            'evenement' => $evenement,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="evenement_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Evenement $evenement): Response
    {
        $form = $this->createForm(EvenementType::class, $evenement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('evenement_index');
        }

        return $this->render('evenement/edit.html.twig', [
            'evenement' => $evenement,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="evenement_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Evenement $evenement): Response
    {
        if ($this->isCsrfTokenValid('delete'.$evenement->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($evenement);
            $entityManager->flush();
        }

        return $this->redirectToRoute('evenement_index');
    }
}

templates/evenement/_delete_form.html.twig
<form method="post" action="{{ path('evenement_delete', {'id': evenement.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ evenement.id) }}">
    <button class="btn">Delete</button>
</form>

templates/evenement/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/evenement/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Evenement{% endblock %}

{% block body %}
    <h1>Edit Evenement</h1>

    {{ include('evenement/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('evenement_index') }}">back to list</a>

    {{ include('evenement/_delete_form.html.twig') }}
{% endblock %}

templates/evenement/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Evenement index{% endblock %}

{% block body %}
    <h1>Evenement index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Sport_id</th>
                <th>Type_id</th>
                <th>Categorie_id</th>
                <th>Nom</th>
                <th>Description</th>
                <th>Date_debut</th>
                <th>Nombre_places</th>
                <th>Image</th>
                <th>Vignette</th>
                <th>Duree</th>
                <th>Date_fin</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for evenement in evenements %}
            <tr>
                <td>{{ evenement.id }}</td>
                <td>{{ evenement.SportId }}</td>
                <td>{{ evenement.TypeId }}</td>
                <td>{{ evenement.CategorieId }}</td>
                <td>{{ evenement.nom }}</td>
                <td>{{ evenement.description }}</td>
                <td>{{ evenement.dateDebut ? evenement.dateDebut|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ evenement.nombrePlaces }}</td>
                <td>{{ evenement.image }}</td>
                <td>{{ evenement.vignette }}</td>
                <td>{{ evenement.duree }}</td>
                <td>{{ evenement.dateFin ? evenement.dateFin|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('evenement_show', {'id': evenement.id}) }}">Montrer</a>
                    <a href="{{ path('evenement_edit', {'id': evenement.id}) }}">Modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="13">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('evenement_new') }}">Créer un évènement</a>
{% endblock %}

templates/evenement/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un évènement{% endblock %}

{% block body %}
    <h1>Ajouter un Evenement</h1>

    {{ include('evenement/_form.html.twig') }}

    <a href="{{ path('evenement_index') }}">Retour aux évènements</a>
{% endblock %}

templates/evenement/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Evenement{% endblock %}

{% block body %}
    <h1>Evenement</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ evenement.id }}</td>
            </tr>
            <tr>
                <th>Sport_id</th>
                <td>{{ evenement.SportId }}</td>
            </tr>
            <tr>
                <th>Type_id</th>
                <td>{{ evenement.TypeId }}</td>
            </tr>
            <tr>
                <th>Categorie_id</th>
                <td>{{ evenement.CategorieId }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ evenement.nom }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ evenement.description }}</td>
            </tr>
            <tr>
                <th>Date_debut</th>
                <td>{{ evenement.dateDebut ? evenement.dateDebut|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Nombre_places</th>
                <td>{{ evenement.nombrePlaces }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>{{ evenement.image }}</td>
            </tr>
            <tr>
                <th>Vignette</th>
                <td>{{ evenement.vignette }}</td>
            </tr>
            <tr>
                <th>Duree</th>
                <td>{{ evenement.duree }}</td>
            </tr>
            <tr>
                <th>Date_fin</th>
                <td>{{ evenement.dateFin ? evenement.dateFin|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('evenement_index') }}">Retour à la liste</a>

    <a href="{{ path('evenement_edit', {'id': evenement.id}) }}">Modifier</a>

    {{ include('evenement/_delete_form.html.twig') }}
{% endblock %}